modLoader = "javafml"
loaderVersion = "[14,)"
updateJSONURL = "https://raw.githubusercontent.com/TheRandomLabs/RandomPatches/misc/versions.json"
issueTrackerURL = "https://github.com/TheRandomLabs/RandomPatches/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/randompatches"
logoFile = "logo.png"
authors = "TheRandomLabs"

[[mods]]

modId = "randompatches"
version = "${file.jarVersion}"
displayName = "RandomPatches"
description = '''
A bunch of miscellaneous patches for Minecraft.
'''
